### ISSUE TITLE
Bearer undefied

### ISSUE THREAD

**Issue by thanhtai9606** [fschick/Keycloak.ASPNet.Angular#1]
I get bearer token is undefied after login
`curl -X 'GET' \
  'http://localhost:5050/api/v1/Article/GetArticles' \
  -H 'accept: text/plain' \
  -H 'Authorization: Bearer undefined'`

**Comment by fschick** [comment]
Could you provide more details?
* What do I have to do to reproduce the situation? 
* Where does the curl line come from?
* Which version of Keycloak is used?

**Comment by thanhtai9606** [comment]
> Could you provide more details?
> 
> * What do I have to do to reproduce the situation?
> * Where does the curl line come from?
> * Which version of Keycloak is used?

I already found issue, we have set Enable Authorization and Authentication, add Standard Flow
like this. After that I must set secret into api client. Because when I import keycloak json keycloak.20.0.2.realm.authorization-uma.json not contain it
![anh](https://user-images.githubusercontent.com/4544983/222381041-1769ee14-3a70-4479-9d42-d29745de0d0c.png)

**Comment by fschick** [comment]
You're talking about the client [`api`](http://localhost:8080/admin/master/console/#/dotnet-ka/clients/9b759c1a-85f5-4b7a-84a7-58c1180049a8/settings)

**Without UMA**
If you don't need [UMA](https://en.wikipedia.org/wiki/User-Managed_Access) (which is a common case, the use of [UMA](https://en.wikipedia.org/wiki/User-Managed_Access) needs to be well considered) you should have a look at the branch [authorization-without-uma](https://github.com/fschick/Keycloak.ASPNet.Angular/tree/authorization-without-uma) or 
[authentication-only](https://github.com/fschick/Keycloak.ASPNet.Angular/tree/authentication-only). They provide an easier set up, especially for beginners.

**With UMA**
The client [`api`](http://localhost:8080/admin/master/console/#/dotnet-ka/clients/9b759c1a-85f5-4b7a-84a7-58c1180049a8/settings) acts as a [resource server](https://www.keycloak.org/docs/latest/authorization_services/#_resource_server_overview) with [UMA](https://en.wikipedia.org/wiki/User-Managed_Access). 'Client authentication' and 'Authorization' should already be set after importing the [realm](https://raw.githubusercontent.com/fschick/Keycloak.ASPNet.Angular/main/keycloak/keycloak.20.0.2.realm.authorization-uma.json). You should not login to the [resource server](https://www.keycloak.org/docs/latest/authorization_services/#_resource_server_overview) directly when using [UMA](https://en.wikipedia.org/wiki/User-Managed_Access) and the 'Standard flow' should not to be set.
Login via the client [`frontend`](http://localhost:8080/admin/master/console/#/dotnet-ka/clients/87aa8b2d-8d68-4572-b26a-8cdc72cfb962/settings) as shown in the [demo code](https://github.com/fschick/Keycloak.ASPNet.Angular/blob/f9ee1fb80a60c373ee32d7ceefe20985b3da5047/source/frontend/src/environments/environment.ts#L10). See [slide 12 'Relation between clients and users'](https://github.com/fschick/Keycloak.ASPNet.Angular/raw/main/slides/Keycloak_ASP.Net_Angular.English.pdf) too.
If you need to access the realm from a trusted (non-web) client which can keep secrets, you should create a separate client for this.

**Comment by thanhtai9606** [comment]
I didn't attend other branch, thank so much :)

**Comment by fschick** [comment]
Do you have any further questions? Or can this issue be closed?
