### ISSUE TITLE
Question (Police branch)

### ISSUE THREAD

**Issue by RodeosML** [fschick/Keycloak.ASPNet.Angular#2]
Thanks for your big work!
Please explain how and what RptInterceptor.js is used for in the backend? (Policy branch)

Do I understand correctly that the client ("frontend" in Keycloak) is needed to exchange tokens and check user rights at the level of interaction between the backend ("api") and the keycloak service?

The second question came about because I first encountered two separate clients in Keycloak ("frontend","api"). 

Thanks for your answers!

**Comment by fschick** [comment]
There is no file named "intercepter.js". Could you check and paste a link to the file in the reprository?

**Comment by RodeosML** [comment]
> There is no file named "intercepter.js". Could you check and paste a link to the file in the reprository?

Sorry, correctly: RptInterceptor.js
Path: https://github.com/fschick/Keycloak.ASPNet.Angular/blob/authorization-via-uma-policy-based/source/backend/Keycloak.ASPNet.Angular.Api/Extensions/RptInterceptor.js

**Comment by fschick** [comment]
RptInterceptor.js is used to enable SwaggerUI to send requests to a resource against an authorization (not authentication) server. To use Keycloak as an authorization server (UMA in OAuth), a RPT token is required with isn't supported by SwaggerUI out-of-the box.

Are you sure you like to use Keycloak as authorization server? It means, authorization is done by Keycloak, not .NET (through roles or policies). This is used by huge companies to let the IT department manage access to applications.

If you need only authentication, the branch [authentication-only](https://github.com/fschick/Keycloak.ASPNet.Angular/tree/authentication-only) is the right for you.

If you like to use Keycloak for authentication and .NET for role or policy based authorization, the branch [authorization-via-roles](https://github.com/fschick/Keycloak.ASPNet.Angular/tree/authorization-via-roles) is the one to use.

**Comment by fschick** [comment]
Do you have any further questions? Or can this issue be closed?

**Comment by fschick** [comment]
Feel free to re-open or create a new issue on further questions.
